packages:
    - 'apps/*'
    - 'packages/*'

catalog:
    '@types/lodash': ^4.17.7
    '@types/node': ^26.2.0
    lodash: ^4.17.21
    typescript: ^5.9.3
    vite: ^5.4.3
    tsup: ^8.2.4
    axios: ^1.7.0
    dayjs: ^1.11.12
