packages:
    - "apps/*"
    - "packages/*"

catalog:
    "@types/lodash": ^4.17.7
    "@types/node": ^22.20.1
    lodash: ^4.18.1
    typescript: ^5.9.3
    vite: ^7.3.6
    tsup: ^8.5.1
    dayjs: ^1.11.12
