import type { ToolType } from "@/config";

export type ToolLayout =
    | "transformer"
    | "editor"
    | "inspector"
    | "generator"
    | "tester"
    | "diff"
    | "utility";

const toolLayouts: Record<ToolType, ToolLayout> = {
    hash: "utility",
    aes: "transformer",
    des: "transformer",
    tripleDes: "transformer",
    rc4: "transformer",
    rabbit: "transformer",
    sm2: "transformer",
    sm4: "transformer",
    rsa: "transformer",
    sign: "tester",
    base64: "transformer",
    json: "editor",
    url: "transformer",
    qrCode: "generator",
    barcode: "generator",
    pinyin: "transformer",
    ip: "inspector",
    code: "editor",
    unicode: "transformer",
    radix: "utility",
    regex: "tester",
    randomString: "generator",
    serialize: "transformer",
    diffs: "diff",
    crontab: "tester",
    websocket: "tester",
    unit: "utility",
    time: "utility",
    uuid: "generator",
    ascii: "inspector",
    variableConversion: "transformer",
    jwt: "inspector",
    hexString: "transformer",
    text: "editor",
    html: "transformer",
    binary: "generator",
    arm: "transformer",
    bcrypt: "tester",
    ipcalc: "inspector",
    sqlFillParameter: "editor",
    httpSnippet: "editor",
    dataValidation: "tester",
    color: "generator",
    hmac: "tester",
    gzip: "transformer",
    punycode: "transformer",
    urlParse: "inspector",
    asn1: "inspector",
    dockerCompose: "editor",
    zhNumber: "utility",
};

const toolMarks: Record<ToolType, string> = {
    hash: "HASH",
    aes: "AES",
    des: "DES",
    tripleDes: "3DES",
    rc4: "RC4",
    rabbit: "RBT",
    sm2: "SM2",
    sm4: "SM4",
    rsa: "RSA",
    sign: "SIG",
    base64: "64",
    json: "{}",
    url: "URL",
    qrCode: "QR",
    barcode: "BAR",
    pinyin: "PY",
    ip: "IP",
    code: "</>",
    unicode: "U+",
    radix: "16",
    regex: ".*",
    randomString: "RNG",
    serialize: "SER",
    diffs: "DIFF",
    crontab: "CRON",
    websocket: "WS",
    unit: "UNIT",
    time: "TIME",
    uuid: "UUID",
    ascii: "ASC",
    variableConversion: "VAR",
    jwt: "JWT",
    hexString: "HEX",
    text: "TXT",
    html: "HTML",
    binary: "BIN",
    arm: "ARM",
    bcrypt: "BCR",
    ipcalc: "CIDR",
    sqlFillParameter: "SQL",
    httpSnippet: "HTTP",
    dataValidation: "CRC",
    color: "HSL",
    hmac: "HMAC",
    gzip: "GZ",
    punycode: "IDN",
    urlParse: "URI",
    asn1: "ASN",
    dockerCompose: "YML",
    zhNumber: "壹",
};

export const getToolMark = (tool: string): string =>
    toolMarks[tool as ToolType] ?? tool.slice(0, 4).toUpperCase();

export const getToolLayout = (tool: string): ToolLayout =>
    toolLayouts[tool as ToolType] ?? "utility";
