import { dirname, join } from "path";
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "fs";

const desktopRoot = join(__dirname, "../../../apps/desktop");

class FileSystem {
    base: string;

    constructor(base = "/") {
        this.base = join(desktopRoot, base);
    }

    // 相对路径转绝对路径
    getPath(path: string) {
        return join(this.base, path);
    }

    // 路径是否存在
    exists(path: string) {
        return existsSync(this.getPath(path));
    }

    // 目录是否存在
    isDir(path: string) {
        return this.exists(path) && statSync(this.getPath(path)).isDirectory();
    }

    // 文件是否存在
    isFile(path: string) {
        return this.exists(path) && statSync(this.getPath(path)).isFile();
    }

    // 写入文件
    writeFile(file: string, content: string = "") {
        const abs = this.getPath(file);
        mkdirSync(dirname(abs), { recursive: true });
        return writeFileSync(abs, content);
    }

    // 读取文件
    readFile(file: string, encoding: BufferEncoding = "utf-8") {
        return readFileSync(this.getPath(file), encoding).toString();
    }

    // 读取目录
    readdir(dir: string, include: string = "") {
        return readdirSync(this.getPath(dir)).filter(item => {
            return !include || item.includes(include);
        });
    }
}

export const fileCoreSrc = new FileSystem("src");

const _buildData: [string[], string[]] = [[], []];
const _buildType: [string[], string[]] = [[], []];

// 编译数据
export const buildData = {
    append(str: string, description?: string) {
        _buildData[1].push(...[...(description !== undefined ? [`// ${description}`] : []), str]);
    },
    prepend(str: string, description?: string) {
        _buildData[0].push(...[...(description !== undefined ? [`// ${description}`] : []), str]);
    },
    write() {
        fileCoreSrc.writeFile(
            "generated/data.ts",
            ["// Generated by packages/config. Do not edit.\n", ..._buildData[0], `\n`, ..._buildData[1]].join("\n"),
        );
    },
};

// 编译类型
export const buildType = {
    append(str: string, description?: string) {
        _buildType[1].push(...[...(description !== undefined ? [`// ${description}`] : []), str]);
    },
    prepend(str: string, description?: string) {
        _buildType[0].push(...[...(description !== undefined ? [`// ${description}`] : []), str]);
    },
    write() {
        fileCoreSrc.writeFile(
            "generated/types.d.ts",
            ["// Generated by packages/config. Do not edit.\n", ..._buildType[0], `\n`, ..._buildType[1]].join("\n"),
        );
    },
};
